# Generated by Django 5.2.14 on 2026-05-17 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=80)),
                ('category', models.CharField(max_length=80)),
                ('budget', models.CharField(max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('duration', models.CharField(blank=True, max_length=80)),
                ('season', models.CharField(blank=True, max_length=80)),
                ('summary', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('hero', models.URLField(blank=True)),
                ('coords_lat', models.FloatField(blank=True, null=True)),
                ('coords_lng', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('location', models.CharField(max_length=120)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=120)),
                ('to_location', models.CharField(max_length=120)),
                ('mode', models.CharField(max_length=80)),
                ('operator', models.CharField(max_length=160)),
                ('fare', models.PositiveIntegerField()),
                ('duration', models.CharField(max_length=80)),
                ('departure', models.CharField(max_length=60)),
                ('travel_class', models.CharField(max_length=120)),
                ('tips', models.TextField(blank=True)),
                ('path', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['from_location', 'to_location', 'mode'],
            },
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='api.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('price', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='api.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120)),
                ('score', models.PositiveSmallIntegerField()),
                ('note', models.TextField(blank=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.destination')),
            ],
        ),
        migrations.CreateModel(
            name='TourGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('members', models.PositiveSmallIntegerField()),
                ('departure', models.CharField(max_length=100)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='api.destination')),
            ],
        ),
    ]
